name: CI - Run Modeling Notebook on Staging

on:
  pull_request:
    branches:
      - main

jobs:
  run-notebook-test:
    runs-on: ubuntu-latest
    steps:
      # Each item under 'steps' must start with a '-' and be indented correctly
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v0.205.0

      - name: Debug Host Value
        run: echo "The host being used is ${{ secrets.DATABRICKS_HOST_STAGING }}"
        
      - name: Deploy and Run Staging Job
        run: databricks bundle deploy -t staging
        working-directory: ./my_mlops_project
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_STAGING }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}