name: CI - Staging Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-notebook-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v0.205.0

      - name: Deploy and Run Staging Job
        run: databricks bundle deploy -t staging
        working-directory: ./my_mlops_project
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_STAGING }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}