# .github/workflows/my_mlops_project-bundle-cd-staging.yml

name: CI - Run Modeling Notebook on Staging

# This action triggers on Pull Requests that target the 'main' branch
on:
  pull_request:
    branches:
      - main

jobs:
  run-notebook-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the code from the Pull Request
      - uses: actions/checkout@v3

      # 2. Set up the Databricks CLI with credentials
      - uses: databricks/setup-cli@v0.205.0

      # 3. Deploy and run the notebook using the Databricks Bundle
      # This command reads your databricks.yml file and executes the staging job
      - run: databricks bundle deploy -t staging
       working-directory: ./my_mlops_project
        env:
          # These secrets are required for authentication
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}